--- 
jobs: 
  build: 
    container: "python:3.9-slim"
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: "Install dependencies"
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - 
        name: "Lint with flake8"
        run: |
            flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      - 
        name: "Run unit tests with nose"
        run: "nosetests -v --with-spec --spec-color --with-coverage --cover-package=app"
      - 
        name: "Upload code coverage"
      - 
        uses: codecov/codecov-action@v2
        with: 
          fail_ci_if_error: true
          files: ./coverage1.xml
          flags: unittests
          token: "${{ secrets.CODECOV_TOKEN }}"
          verbose: true
          version: v0.1.13
name: "CI workflow"
true: 
  pull_request: 
    branches: 
      - main
  push: 
    branches: 
      - main